### ISSUE TITLE
Feature request: add elements key-tweaking functionality

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-miniscript#151]
Needed to remove the broken `contracthash` module from rust-bitcoin, see https://github.com/rust-bitcoin/rust-bitcoin/pull/365

I'll take this on because I directly use this API in Liquid and have some thoughts about how it could be improved.

**Comment by sanket1729** [comment]
closing duplicate (#64) in favour of this since one tends to forget old issues :).

**Comment by tcharding** [comment]
Can we close this? https://github.com/rust-bitcoin/rust-bitcoin/pull/871 was merged in `rust-bitcoin` and includes the comment:

> Yes, elements-miniscript needs this functionality. Will re-implement this over there

**Comment by apoelstra** [comment]
Yeah, let's close it here. It definitely belongs in elements-miniscript (where there are pegin descriptors) and not here (where there are not).
