### ISSUE TITLE
Speed of descriptor derivation

### ISSUE THREAD

**Issue by RCasatta** [rust-bitcoin/rust-miniscript#163]
I noticed deriving a bunch of addresses from a descriptor containing a single xpub was quite slow compared to `ExtendedPubKey::derive`, the reason is that secp context is initialized at every derivation here:
https://github.com/rust-bitcoin/rust-miniscript/blob/5714f091bc30676b6e6140b23cee4bdd559a4f78/src/descriptor/mod.rs#L330

I am not sure which is the best way to avoid initialization at every derivation, since passing secp as parameter "pollute" the API and I don't see an easy way to add secp as field of `DescriptorXPub` since there would be problem with the derived trait of `DescriptorXPub` such `Clone`. Also, I don't think `lazy_static!` globally is a viable option.

Are there plan to improve this?

**Comment by sanket1729** [comment]
I think adding a parameter is the way to go. Similar API's in rust-bitcoin take secp context as a parameter.
`sk.public_key(&secp)` . 

Thanks for bringing this up, I think pollution is unavoidable and we should probably prefer speed, cc @apoelstra .

**Comment by afilini** [comment]
Alternatively I guess you could add a "global" context initialized with something like `lazy_static`

**Comment by apoelstra** [comment]
Yeah, we definitely can't put a static variable into a general purpose library.

I'm not thrilled about polluting the API but it probably does make sense to have a secp context for converting to public keys. An interesting question though is what context capabilities should we require?

**Comment by sanket1729** [comment]
To address this specific issue, it is possible to modify the function 
https://github.com/rust-bitcoin/rust-miniscript/blob/5714f091bc30676b6e6140b23cee4bdd559a4f78/src/descriptor/mod.rs#L713

to use a secp reference instead of calling `to_public_key`. 
But other functions in the library that rely on `ToPublicKey` for `witness_script/address/etc` would still be slow.

**Comment by apoelstra** [comment]
We're going to have a similar problem with Taproot/p2c derivation ... I think we should change the `ToPublicKey` method to take a secp context. And I guess parameterize `ToPublicKey` over the required secp functionality.

I guess in rust-secp we also ought to reintroduce a dummy context so users without any context, who don't need one, would still be able to comfortably use the library.

**Comment by sanket1729** [comment]
Maybe an Option<SecpContext>?

**Comment by apoelstra** [comment]
Then `to_public_key` would need to be able to fail, which kinda sucks.

BTW what happens now when you parse a wildcard-containing path and you call `to_public_key` on it?

**Comment by sanket1729** [comment]
The wildcard is ignored.

**Comment by apoelstra** [comment]
That seems wrong to me. I don't think `DescriptorPublicKey` should implement `ToPublicKey`.

**Comment by sanket1729** [comment]
Fixed by #166
