### ISSUE TITLE
Support for sortedmulti descriptor script expression?

### ISSUE THREAD

**Issue by LightningK0ala** [rust-bitcoin/rust-miniscript#164]
Any plans to add support for the `sortedmulti` script expression? Some wallets like Spectre and hww's like Coldcard produce / expect BIP67 format.

This would improve compatibility for bdk, which uses rust-miniscript as a dependency and doesn't easily allow for loading descriptors with sortedmulti.

**Comment by sanket1729** [comment]
Yes, I plan to add support for these in the next week or two.
