### ISSUE TITLE
Document under which cases `max_satisfaction_weight` returns None

### ISSUE THREAD

**Issue by LLFourn** [rust-bitcoin/rust-miniscript#194]
See: https://docs.rs/miniscript/4.0.0/miniscript/descriptor/enum.Descriptor.html#method.max_satisfaction_weight

I am unsure about what to do in the None case or why it would happen.

**Comment by sanket1729** [comment]
I will add a PR to doccomment. It will return `None` if Miniscript is equivalent to `0` or `false`. In other words, there cannot be any satisfactions for such miniscripts.

**Comment by sanket1729** [comment]
Fixed by #217. There are no confusing Option returns anymore.
