### ISSUE TITLE
no_std support

### ISSUE THREAD

**Issue by justinmoon** [rust-bitcoin/rust-miniscript#201]
Let's make a tracking issue for this

**Comment by apoelstra** [comment]
Relevant:
- https://github.com/rust-bitcoin/rust-bitcoin/pull/528
- https://github.com/rust-bitcoin/rust-bitcoin/issues/549 (may affect how rust-bitcoin approaches nostd)
- https://github.com/rust-bitcoin/bitcoin_hashes/pull/107

I think getting rust-miniscript to work on embedded platforms (and wasm) is a super high-importance project.

**Comment by mcroad** [comment]
Any news on this front? What else is needed for no_std support?

**Comment by sanket1729** [comment]
Rust bitcoin supports embedded from https://github.com/rust-bitcoin/rust-bitcoin/pull/603. I don't have any embedded experience, but I think we would need something similar to the above for rust-miniscript. 

I am currently working on taproot support for rust-miniscript, but any contributions towards this are welcome.
