### ISSUE TITLE
thresh checks are different from specs

### ISSUE THREAD

**Issue by stepansnigirev** [rust-bitcoin/rust-miniscript#241]
According to the specs (http://bitcoin.sipa.be/miniscript/) `thresh` operator in miniscript (not in policy) should only accept `1 < k < n`, but in this implementation `thresh` is allowed with `1 < k <= n`.

Can you clarify what should be changed - the specs or the implementation?

Examples:
```
wsh(thresh(5,pk(036070b1f2995d8ffda8478ef55affd39795689a3982d54b12180397b1ad1f5f75),s:pk(026515fa7603c10c44f6d316ae7592b5899d46d87ac1e574ec53de8b59f95efad6),s:pk(038c8f919f70062c084376223fd8b4f0c08958e70499df496411dde83a1bb64b0d),s:pk(02d0ea7084e344b56625277b074d15a15301b9d96b0b2dd9fc905e01fc3de408e1),sdv:after(100)))
```
is converted to the following raw bitcoin script:
```
21036070b1f2995d8ffda8478ef55affd39795689a3982d54b12180397b1ad1f5f75ac7c21026515fa7603c10c44f6d316ae7592b5899d46d87ac1e574ec53de8b59f95efad6ac937c21038c8f919f70062c084376223fd8b4f0c08958e70499df496411dde83a1bb64b0dac937c2102d0ea7084e344b56625277b074d15a15301b9d96b0b2dd9fc905e01fc3de408e1ac937c76630164b16968935587
```
and `desc.sanity_check().is_ok()` returns `true`

If I use `thresh(1,...)` it also can be converted to raw script, but at least `desc.sanity_check().is_ok()` returns `false`.

**Comment by sanket1729** [comment]
As per my last discussion with Pieter and Andrew, we are supporting `thresh` for `1<=k<=n`. If that is not supported in the codebase, it is a bug.

**Comment by darosior** [comment]
@sanket1729 the point is that we do, but this makes us incompatible with the C++ implementation.

ref https://github.com/rust-bitcoin/rust-miniscript/pull/242

**Comment by sanket1729** [comment]
Both the implementations are not consistent with the spec.
