### ISSUE TITLE
Cryptographically unreachable code when deriving descriptor

### ISSUE THREAD

**Issue by darosior** [rust-bitcoin/rust-miniscript#245]
```
thread '<unnamed>' panicked at 'internal error: entered unreachable code: cryptographically unreachable: secp: malformed or out-of-range secret key', /home/darosior/.cargo/registry/src/github.com-1ecc6299db9ec823/miniscript-5.1.0/src/descriptor/key.rs:453:31
```

Happened when fuzzing my transaction chain creation (deriving a Miniscript descriptor). Still need to dive into it but wanted to share it first.

EDIT: can't reproduce when not in fuzzing mode.. Weird.

EDIT 2: i fixed it on my end by not generating random keys in the fuzzing target, but i guess it shouldn't happen anyways? I'll write a fuzz target here reproducing it asap.

**Comment by apoelstra** [comment]
are any of your recent PRs related to this?

**Comment by darosior** [comment]
No
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by sanket1729** [comment]
If you are using it `cfg(fuzzing)` mode, it has a hand-baked crypto implementation that would break cryptographic invariants.
