### ISSUE TITLE
Weird behavior for Policy::minimum_n_keys

### ISSUE THREAD

**Issue by danielabrozzoni** [rust-bitcoin/rust-miniscript#264]
`minimum_n_keys` returns 0 when it encounters `Policy::Unsatisfiable`, this leads to some strange behavior with policies such as:
```
or(UNSATISFIABLE,and(pkh(alice_pkh),pkh(bob_pkh)))
```
where `minimum_n_keys` returns 0, even though the minimum number of keys for satisfying that policy is 2.

**Comment by sanket1729** [comment]
This is indeed a bug. I think we should update the method to return an option.

**Comment by danielabrozzoni** [comment]
I agree, even though returning an Option *might* make the code a bit messier.
Can I try working on this? :)

**Comment by sanket1729** [comment]
Yes, all yours :)
