### ISSUE TITLE
7.0 RC1 release

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-miniscript#292]
Will it be possible to have it with `tr` descriptors merged?

**Comment by sanket1729** [comment]
Sorry, I was sick for the past few days. Yes, taproot descriptors and planned and implemented. I have a local branch with taproot descriptor support, but there are still some changes discussed [here](https://github.com/bitcoin/bitcoin/issues/24114) which I believe would simplify our design significantly. If there is some consensus there, I would like to include it in this release. If this takes some time, we can ship a RC without it.

Secondly, It would *greatly* simplify rust-miniscript implementation of #267 if we have https://github.com/rust-bitcoin/rust-secp256k1/issues/378.

**Comment by dr-orlovsky** [comment]
Can you pls do a brief update of what is left to get Taproot-enabled miniscript RC? Me and my colleagues are willing to help as much as possible. Also, it will add the related issues/PRs to the Taproot project in rust-bitcoin GitHub org.

**Comment by sanket1729** [comment]
We are very close. Possibly this week! https://github.com/rust-bitcoin/rust-secp256k1/pull/384 has ACK and will unblock everything in rust-bitcoin land. 

As far as rust-miniscript. I think the open PRs should get in quickly. The main pieces are #301, #305, and a final PR that adds integration tests which I will open in a few hours. Review for those would be appreciated and I will be prompt in addressing it.

**Comment by sanket1729** [comment]
@dr-orlovsky @LLFourn and others, 7.0.0-rc.1 has been tagged and published.
