### ISSUE TITLE
Change the parameters of `derived_descriptor`

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-miniscript#302]
The parameter for `secp` should go first, `idx` should go second. 

See:
https://github.com/rust-bitcoin/rust-miniscript/blob/6a89bd0d1aa2a4b2e78d624276471727bf61b753/src/descriptor/mod.rs#L591

Update the `xpub_descriptors.rs` example to use this API instead of `derive`

**Comment by Eunoia1729** [comment]
Hi @sanket1729 ! I'd like to work on this
