### ISSUE TITLE
Extend the integration tests to test failure conditions

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-miniscript#317]
In #309, we added integration tests to check descriptor satisfaction logic. We should extend the `test_desc_satisfy` https://github.com/rust-bitcoin/rust-miniscript/blob/75ff6275c320a748b9280f3b6eddd481d576115f/integration_test/src/test_desc.rs#L43 .
to return result. And test misc failure test cases for descriptors. 

- Add tests for testing each fragment of miniscript from bitcoin reference: `bitcoin.sipa.be/miniscript`. This can be a bit challenging but is a good resource to get started and understand miniscript hands-on.
- Add tests for failure paths
- Add tests for various sighash modes.

**Comment by sujalharkut** [comment]
Hi @sanket1729 ! I'd like to work on this

**Comment by dunxen** [comment]
Working on this.

**Comment by kanishk779** [comment]
@dunxen could you please let me work on this issue, as I have started understanding the codebase and was looking forward to contributing to the organisation in the coming summer.

**Comment by dunxen** [comment]
Hi @kanishk779. Yes, of course! I have not done too much yet. 🙂

**Comment by sanket1729** [comment]
This was merged in #429
