### ISSUE TITLE
First taproot script-path-spending tx with miniscript 0.7.0 RC1

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-miniscript#322]
Wanted to share my excitement with you.

Just made a first script-path-spending transaction with my miniscript-based [descriptor wallet](https://github.com/LNP-BP/descriptor-wallet) library:

https://mempool.space/testnet/tx/62cfb109aa4c20ed6b2daad39ef0a0ed0bb650ba575ad35e940c8f8c4b6a9e2d

The wallet descriptor is the following:
```
tr(acc0, {
   multi_a(3, acc10, acc11, acc12), {
     and_v(
       v:multi_a(2, acc10, acc11, acc12),
       after(10)
     ),
     and_v(
       v:multi_a(1, acc10, acc11, acc12),
       after(100)
     )
   }
})
```

<details>
<summary>account xpub index</summary>

    acc0  m=[877c9433]/86h/1h/0h=[tpubDC7mz8DJG7cy72MomPR2TmkfA6kjqYkEtYPHigBcycRaaPGD4fgmS8WWADEPNN685xVepi8nee1xGEYR33iNj9hy5HpqhtAKTT2uq4uq7jv]/*/*
    acc10 m=[877c9433]/86h/1h/10h=[tpubDC7mz8DJG7cyYEWffExngTpWvjn6rZqaAkugaiHKVzsw9jA5fL7Ch8G2KSxGpraZZNYEKaH4uDExLbtE5ySBA49ZZfP6aXjvAHVyyxjEEeu]/*/*
    acc11 m=[877c9433]/86h/1h/11h=[tpubDC7mz8DJG7cyb3BEFXtK1FbvoD3Y81RTjqUUvkaZDXbQExaaMAg1gNy1yLQeRYbL94eFfQ4WymxksrWJJYCLh7Fwrs1e5wG1TwAsKrruUS9]/*/*
    acc12 m=[877c9433]/86h/1h/12h=[tpubDC7mz8DJG7cycqGg8AnwnvRT2Gwwgr9tf6Xv8ejs6Ec5gcg1PPnukYnwUADsb6EQPT3SdHg6zrC9WRwoPUan2PpaqtNRbUJxWZJkGmeh1HZ]/*/*

</details>

The transaction spends via 3-of-3 branch of the taptree in the descriptor.

PS. The library uses different signer, not the one from miniscript (it was required to support P2C tweaks and proprietary keys) - but uses finalizer from this miniscript library

**Comment by sanket1729** [comment]
Awesome. Congratulations!

**Comment by sanket1729** [comment]
Congratulations again. Your reviews also made this possible. Closing this as it is not really an issue

**Comment by dr-orlovsky** [comment]
Can we pls transform this issue into a discussion in the "Feedback" section?
