### ISSUE TITLE
Consider impl MiniscriptKey for secp256k1::PublicKey

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-miniscript#326]
`secp256k1::PublicKey` is the only type that can be used to derive both `XOnlyPublicKey` and `bitcoin::PublicKey`. This pattern is useful a lot in downstream wallets, when they do not know which key type will be held by descriptors.

**Comment by apoelstra** [comment]
Yeah this seems like a good idea.

Our decision not to use `secp256k1::PublicKey` predates the `Miniscript::is_uncompressed` method, which now can simply be set to constant `false` for secp key types.

**Comment by dr-orlovsky** [comment]
@apoelstra did that in #327
