### ISSUE TITLE
Constant TAPROOT_MAX_NODE_COUNT duplicates rust-bitcoin one

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-miniscript#334]
The constant `TAPROOT_MAX_NODE_COUNT` should be replaced with rust-bitcoin `TAPROOT_CONTROL_MAX_NODE_COUNT`

**Comment by RM07** [comment]
Can I take this issue ?

**Comment by dr-orlovsky** [comment]
I do not see why not, but I am not a maintainer here, so let's see what @sanket1729 will think

**Comment by Eunoia1729** [comment]
Hey @RM07 ! A PR has already been opened against this issue. Your review there would be much more appreciated over opening another PR.
