### ISSUE TITLE
Use upstream `script_code_p2wpkh` API

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-miniscript#364]
After https://github.com/rust-bitcoin/rust-bitcoin/pull/954 and rust-bitcoin 0.29 release, we can use the new API to cleanup `script_code_p2wpkh` here to cleanup manual calculation in `psbt/mod.rs`

**Comment by tcharding** [comment]
I can't find any code manually building the script code - is this issue still live?

**Comment by sanket1729** [comment]
https://github.com/rust-bitcoin/rust-miniscript/blob/7664570e7d4401f457932633455d42660a00b6cb/src/psbt/mod.rs#L1258
