### ISSUE TITLE
Mark Miniscripts with a keyhash inside `pk_h()` as unsafe

### ISSUE THREAD

**Issue by darosior** [rust-bitcoin/rust-miniscript#368]
We currently support representing a `pk_h()` fragment (as well as the `pkh()` alias for that matter) with a keyhash parameter instead of the key itself.
https://github.com/rust-bitcoin/rust-miniscript/blob/148112c0cd392e79eb0d37467a823658c710b055/src/miniscript/decode.rs#L136-L137

This has attractive properties, such as keeping the possibility to roundtrip through Script with no need for external material. However, i believe it can be pretty surprising to say the least when used as an actual descriptor. Take a situation where Alice and Bob create this very simple Miniscript descriptor together:
```
wsh(or_d(pkh(Alice's key hash),pk(Bob's key)))
```
Bob analyzes the Script with rust-miniscript which tells it that it is a sane (and safe) Miniscript descriptor to use, from which it can unconditionally spend from. He sends coin to it, and once comes the time he actually wants to spend from the Script.. Surprise! He actually needs to be able to dissatisfy `pk(Alice's key hash)` for which he needs the preimage of the key hash, which is not part of the descriptor.

At the end of the day, it's the same as for any partial descriptor (https://github.com/bitcoin/bitcoin/issues/24114), you can't make any assumption about it. We should communicate that to the user.

**Comment by darosior** [comment]
I have updated the issue following discussions on IRC, to remove the confusing attempt to explain this using the Miniscript type system.
The gist is essentially that we should not expect users to know that a `pk_h(key hash)` may make the descriptor **unspendable** for them if they don't have the key, *and even if the `pk_h` isn't part of "their branch"*.

**Comment by sanket1729** [comment]
> Bob analyzes the Script with rust-miniscript which tells it that it is a sane (and safe) Miniscript descriptor to use, from which it can unconditionally spend from.

Bob should and must analyze using the `DescriptorPublicKey` type. If it fails to parse, Bob should fail!

**Comment by darosior** [comment]
Reading the [changelog](https://github.com/rust-bitcoin/rust-miniscript/blob/master/CHANGELOG.md#800---october-20-2022), i think this was addressed in the latest release and this issue can be closed?

**Comment by apoelstra** [comment]
Yes, I believe this issue is resolved by the separation of pkh into pkh(pk) and rawpkh(hash).
