### ISSUE TITLE
Double the codebase for ToPkCtx remains

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-miniscript#396]
A long time ago we had extensive comments throughout the codebase explaining how to use ToPkCtx. We have moved past that with the new TranslatePk* methods. We should double-check the codebase to see if there are still some comments. Found one here: https://github.com/rust-bitcoin/rust-miniscript/pull/387#discussion_r868601191

**Comment by tcharding** [comment]
I rekon this can be closed, grepping for the following gave no results (all with `git grep -i`)
- topkctx
- pkctx

And the output of `git grep -i '[a-z]ctx' seems sane.

**Comment by sanket1729** [comment]
Thank you, indeed this can be closed.
