### ISSUE TITLE
[Chasing Concept ACK] Add Pk: FromStr and Pk::Hash bound to MiniscriptKey trait

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-miniscript#423]
This will cleanup a lot of code where we have `where Pk: FromStr, Pk:: Hash: FromStr ` and the same bounds about errors. This will restrict MiniscriptKey users to write a FromStr implementation. But I think, it's not really limiting and will result in bunch of cleanup for us

```rust
    Pk: MiniscriptKey + str::FromStr,
    Pk::Hash: str::FromStr,
    <Pk as FromStr>::Err: ToString,
    <<Pk as MiniscriptKey>::Hash as FromStr>::Err: ToString,
```

**Comment by sanket1729** [comment]
If you don't need `FromStr`, it can be implemented as `panic!` or `unreachable!`?

**Comment by apoelstra** [comment]
I don't think it's reasonable for a user to have to read the entire codebase checking under what conditions the `FromStr` impl is actually used, and to trust that this won't change in the future.

**Comment by sanket1729** [comment]
> I don't think it's reasonable for a user to have to read the entire codebase checking under what conditions the FromStr impl is actually used, and to trust that this won't change in the future.

Fair point

**Comment by apoelstra** [comment]
We could add another dummy trait though which simply depends on the four lines that you posted. I agree that it's super ugly to have all these conditions repeated over and over.

**Comment by sanket1729** [comment]
It is getting worse with new Translate API overhaul that I am working on. 

```rust
    Pk: MiniscriptKey + str::FromStr,
    Pk::Hash: str::FromStr,
    Pk::Sha256Hash: str::FromStr,
    Ctx: ScriptContext,
    <Pk as str::FromStr>::Err: ToString,
    <<Pk as MiniscriptKey>::Hash as str::FromStr>::Err: ToString,
    <<Pk as MiniscriptKey>::Sha256Hash as str::FromStr>::Err: ToString,
```

More lines would be added to each Hash256 associated type, Older, After etc.

**Comment by sanket1729** [comment]
Will look for more cleaner solutions without having the FromStr requirement
