### ISSUE TITLE
New release with rust-bitcoin 0.29

### ISSUE THREAD

**Issue by josediegorobles** [rust-bitcoin/rust-miniscript#452]
Hi, rust-bitcoin 0.29 is released yet, when is planned a new release of rust-miniscript with this version?

**Comment by tcharding** [comment]
No plans around here, its chaos mode :) I'm guessing soon as someone does the patch to upgrade the dependency. I'll try get to it today unless someone beats me to it.

**Comment by tcharding** [comment]
FYI the following crates have to upgrade before we can upgrade `rust-miniscript`
- rust-bitcoincore-rpc: https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/234
- bitcoind

And latter requires the former to be released first.

**Comment by josediegorobles** [comment]
> FYI the following crates have to upgrade before we can upgrade `rust-miniscript`
> 
> * rust-bitcoincore-rpc: [Upgrade bitcoin dependency rust-bitcoincore-rpc#234](https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/234)
> * bitcoind
> 
> And latter requires the former to be released first.

Ok, first is done yet, is turn now of bitcoind (this issue: https://github.com/RCasatta/bitcoind/issues/82)

**Comment by josediegorobles** [comment]
Hi, now all the others are done, isn't it? What's the state of this issue?

**Comment by josediegorobles** [comment]
It's this PR: https://github.com/rust-bitcoin/rust-miniscript/pull/450

**Comment by tcharding** [comment]
That's the bitcoin upgrade, I don't know what else is to be done but there will be a release PR as well, that hasn't been done yet. You can do the release PR if you are keen, means writing release notes and bumping the version. Here are some examples
- https://github.com/rust-bitcoin/rust-bitcoin/pull/944/files
- https://github.com/rust-bitcoin/rust-miniscript/pull/262/files

**Comment by josediegorobles** [comment]
Ok I can see it

**Comment by josediegorobles** [comment]
Hi @tcharding i made a PR: https://github.com/tcharding/rust-miniscript/pull/1
I put 7.1.0 version and the bump version on the CHANGELOG. ¿It's correct the version? ¿What other things must be in the CHANGELOG?

**Comment by sanket1729** [comment]
@josediegorobles, your work looks great. For this particular case, I think it is best if the changelog PRs are made by maintainers. I made a draft PR for release #462, hope you don't mind me adding some changes there.

**Comment by tcharding** [comment]
> I think it is best if the changelog PRs are made by maintainers.

Oh sorry, that was my fault then - I thought you might be busy and going through all the previous PRs is kinda tedious. I'll keep this in mind in future.

**Comment by josediegorobles** [comment]
The new release is with this draft PR: https://github.com/rust-bitcoin/rust-miniscript/pull/462

**Comment by sanket1729** [comment]
> Oh sorry, that was my fault then - I thought you might be busy and going through all the previous PRs is kinda tedious. I'll keep this in mind in future.

No worries. Sorry for the effort you and Jose put in :(.  It's not a hard rule that maintainers must create a changelog, but mostly they have a good idea of which changes are important to highlight.

**Comment by josediegorobles** [comment]
> > Oh sorry, that was my fault then - I thought you might be busy and going through all the previous PRs is kinda tedious. I'll keep this in mind in future.
> 
> No worries. Sorry for the effort you and Jose put in :(. It's not a hard rule that maintainers must create a changelog, but mostly they have a good idea of which changes are important to highlight.

It's very reasonable to do it like that. No worries, and thank you all for your effort
