### ISSUE TITLE
Flaky CI with integration tests

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-miniscript#464]
Our CI integration tests run JSON RPC commands on an HTTP server local node. I suspect this would have to do timeouts in our RPC commands. If this reoccurs again, we should increase the timeout. 

Example fail run: https://github.com/rust-bitcoin/rust-miniscript/actions/runs/3134123490/jobs/5088288888#step:4:292

Rerunning the CI fixed it again

**Comment by apoelstra** [comment]
I'm going to close this. We haven't had CI flakiness in a while.
