### ISSUE TITLE
Multipath descriptors support

### ISSUE THREAD

**Issue by darosior** [rust-bitcoin/rust-miniscript#469]
Multipath descriptors were proposed as a way to optimize the descriptor backup for the common case of having two derivation chains (one for receiving addresses, one for change).

A BIP was proposed a couple months ago: https://github.com/bitcoin/bips/pull/1354. There is an implementation in Bitcoin Core at https://github.com/bitcoin/bitcoin/pull/22838.

It was previously discussed at length in https://github.com/bitcoin/bitcoin/issues/17190.

I think it would be helpful for us to support them. What do you think?

**Comment by apoelstra** [comment]
Yes, I do think we should support them.

**Comment by darosior** [comment]
I'm working on something. It's a quite invasive change, i'm adding a new variant of `DescriptorPublicKey` that contains a `DescriptorMultiXKey`. I think i'll have to change some interfaces as some assumptions necessarily don't hold anymore, for instance
https://github.com/rust-bitcoin/rust-miniscript/blob/9ea094cf825e7775e51848d7f32a391b990e3bed/src/descriptor/key.rs#L406-L411

**Comment by darosior** [comment]
I've opened a WIP pull request to discuss the approach. https://github.com/rust-bitcoin/rust-miniscript/pull/470
