### ISSUE TITLE
We should not be running pkh logic through rawpkh

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-miniscript#483]
See for example https://github.com/rust-bitcoin/rust-miniscript/blob/master/src/miniscript/satisfy.rs#L937 (not sure if there are any other examples). Here we have a public key, convert it to a hash, then look up the key again from that.

In #481 (the "planning module" PR) I am suggesting that we work with `DescriptorPublicKey`s rather than `DefinitePublicKey`s, which means that we may be working with keys where we don't know their hash160 and can't do this lookup. So in addition to being unnecessary, this roundtrip through a hash may become wrong.

**Comment by sanket1729** [comment]
> So in addition to being unnecessary, this roundtrip through a hash may become wrong.

I agree this is unnecessary, but why can it be wrong?

**Comment by apoelstra** [comment]
@sanket1729 imagine we had a satisfier that simply did not have a map from hashes to public keys (because it assumes we have no raw pkhs), so the hash lookup would always return `None`.
