### ISSUE TITLE
Descriptor doesn't roundtrip in fuzz test

### ISSUE THREAD

**Issue by RCasatta** [rust-bitcoin/rust-miniscript#490]
miniscript version: `8.0.0`

fuzz_target: `roundtrip_descriptor`

data: `b"c:pk_h()"`

result:
```
---- tests::roundtrip_descriptor stdout ----
thread 'tests::roundtrip_descriptor' panicked at 'assertion failed: `(left == right)`
  left: `[B/nduesm]c:[K/nduesm]pk_h(DummyKey)`,
 right: `pkh(DummyKey)`', fuzz_targets/roundtrip_descriptor.rs:14:9
```

**Comment by apoelstra** [comment]
Closing this. The fuzztest no longer fails on this input, though on a cursory check I'm not certain how or when we fixed it.

**Comment by sanket1729** [comment]
@apoelstra 

This sounds more like fuzz test needs fixing up for a canonical form. The descriptor is not expected to be roundtrip.

**Comment by apoelstra** [comment]
Agreed. Will try to revisit this after I've messed with the descriptor parser more, to see if there's some sort of "canonicalizer" I can extract from it.
