### ISSUE TITLE
`DefiniteDescriptorKey` does not expose a way to get the key out if it's internally a single key

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-miniscript#491]
Right now if you have a `DescriptorPublicKey` and you convert it to a `DefiniteDescriptorKey` with `at_derivation_index`, you lose any good way to determine whether you have a single key or not, and you lose access to the key.

With `DescriptorPublicKey` you can just match on it since it's a public enum and is either `Single` or `XPub`. But `DefiniteDescriptorKey` is an opaque struct.

Consider the case where you have a descriptor public key, potentially with hardened wildcards, but it's user-provided so it could be anything. To get a specific public key out of this you need to talk to a hww. With a `DescriptorPublicKey` you'd match on the key; for `Single` you directly pull the key out, and for `Xpub` you pass the derivation path over USB to your hww and use the result. But now with `DefiniteDescriptorKey` you're forced to call `derive_public_key`, which requires you have a secp context available, and only after this fails do you know that you need to switch to the hww.

I'm not sure what the best solution here is. Probably just a `single_key -> Option<SinglePub>` method on `DefiniteDescriptorKey`.

**Comment by apoelstra** [comment]
Ah, if we have an owned `DefiniteDescriptorKey` you can convert it back to a `DescriptorPublicKey` with `From`. We should add a similar conversion method for a borrowed `DefiniteDescriptorKey` and also a dedicated method.

**Comment by engenegr** [comment]
Hi,  @apoelstra,
do I understand it right that there are no convenient ways to use `DescriptorPublicKey` and `DescriptorSecretKey` for signing PSBT? This issue leaves such impression since I already going through KeyMap and trying to match DescriptorSecretKey, extract key and sign with it and obtaining `MiniscriptError(CouldNotSatisfy)` in the end.

**Comment by apoelstra** [comment]
@engenegr no, this issue doesn't really have anything to do with PSBT or with signing ergonomics. It is also fixed by #492 and should be closed.

Having said that, if you are going trying to sign with in-memory keys, you will need to have a map (of some sort) from public keys to private keys. This library doesn't really provide facilities for that map, or any operations with secret keys, really, other than to support serializing or deserializing private descriptors.
