### ISSUE TITLE
DescriptorPublicKey derives different key to derive_priv

### ISSUE THREAD

**Issue by engenegr** [rust-bitcoin/rust-miniscript#494]
While trying to import descriptor with private key and derivation path, and signing a transaction, I ran into that PSBT can't be finialized due to various errors. I wont discuss all issues stemming `from Descriptor::parse_descriptor` but I'd like to point out that I get different public keys where they should be the same.

For this piece
```Rust
        let bkp0_root_private = ExtendedPrivKey::from_str("tprv8ZgxMBicQKsPerMTN7nhwCpqaAEPkaBCDeE8c9ekAY1xhPmF3HM9r3oz33V8JTwsJYp9FYLDQumLzNssLo6UNMNesVwPP1KcgA5atrSqU2w").unwrap();
        let bkp0_derived_private = bkp0_root_private
            .derive_priv(&secp, &DerivationPath::from_str(
                format!("m/84'/1'/1/0/{index}").as_str()
            ).unwrap())
            .unwrap();
        let bkp0_derived_public = ExtendedPubKey::from_priv(&secp, &bkp0_derived_private);
        println!("Public backup key 0 {:?}", bkp0_derived_public.to_pub()); 
```
I have an output
```
Public backup key 0 PublicKey { compressed: true, inner: PublicKey(af14811cefe6dab94efdd14aa89315fc291db6d8abf2262403ae9d487aaccf3c253cb287ae4dd8f4ceb6f568ea7a0290815767fef9271e15bb653cb7ef1e972a) }
```

and for this
```Rust
        let desc_str = "wsh(t:or_c(pk(02a7d30ac6b0cd55b6868f5a65aff1dbdaa18f4315fe04de809fffb2899340ae0f),v:multi(1,[255f0d9b/84'/1'/1/0]tprv8ZgxMBicQKsPerMTN7nhwCpqaAEPkaBCDeE8c9ekAY1xhPmF3HM9r3oz33V8JTwsJYp9FYLDQumLzNssLo6UNMNesVwPP1KcgA5atrSqU2w/*,02f17cce1778c101e3b0ac5c76997af3752b0a221b1ebffc23af679328f3f5d6fc,02350b5a9a12df96579d150f3f751de416e58a67f2ba9bc99f6964b7a48a79042b)))";
        
        let (desc, keys) = Descriptor::parse_descriptor(&secp, desc_str).unwrap();
        
        if keys.len() < 1 {return Err(ZeroPrivateKeys)};

        for (public, private) in &keys {
            println!("{:?}", &public.full_derivation_path().to_string());
            println!("{:?}", private);
            let child = public.clone().at_derivation_index(0);
            println!("{:?}", child);
            println!("{:?}", child.full_derivation_path().to_string());
            println!("{:?}", child.to_public_key());
            // 033ccfac7a489dae032426f2abd8b61d29fc1593a84ad1fd4eb9dae6ef1c8114af
        }
```

I have 
```
        "m/84'/1'/1/0"
XPrv(DescriptorXKey { origin: Some((255f0d9b, m/84'/1'/1/0)), xkey: ExtendedPrivKey { network: Testnet, depth: 0, parent_fingerprint: 00000000, child_number: Normal { index: 0 }, private_key: SecretKey(#09e17fda6bbd289d), chain_code: c6bdbc4ab1185a5ce55526a7210754bdad9676c2f61feae2ceeede1399826620 }, derivation_path: m, wildcard: Unhardened })
DefiniteDescriptorKey(XPub(DescriptorXKey { origin: Some((255f0d9b, m/84'/1'/1/0)), xkey: ExtendedPubKey { network: Testnet, depth: 0, parent_fingerprint: 00000000, child_number: Normal { index: 0 }, public_key: PublicKey(3cd26f95f159c62eace012014df688b987e8df58779d2faa6e36f8e7bab7f9cec2227d5d848ca1e5d4ff9a0669a67a9bec0866d903654372ca4fb8f4614e5f6f), chain_code: c6bdbc4ab1185a5ce55526a7210754bdad9676c2f61feae2ceeede1399826620 }, derivation_path: m/0, wildcard: None }))
"m/84'/1'/1/0/0"
PublicKey { compressed: true, inner: PublicKey(3e04d0535511737be746035a944c9ab74f580af5abccefe4aa5a7945e7470a0d287761eb7c4175b6e07e22b1110940926edb082198b33952a31504b905a6cb4a) }
```

Paths are the same but keys are different and I cant use descriptor with private key. I can only make some `ExtendedPubKey` and `ExtendedPrivKey` object, assemble PSBT and it will be finalized.

**Comment by sanket1729** [comment]
I think you are confusing two things. The origin information and derivation path:

1) Origin `[255f0d9b/84'/1'/1/0]KEY/84'/1'/1/0/*`: This tells the wallet this `KEY` is obtained by using the derivation path on the key with fingerprint `255f0d9b`. This origin information plays no role in deriving new keys
2) The derivation path: /84'/1'/1/0/ gives the derivation information about the path. In your example if you replace 
`[255f0d9b/84'/1'/1/0]tprv8ZgxMBicQKsPerMTN7nhwCpqaAEPkaBCDeE8c9ekAY1xhPmF3HM9r3oz33V8JTwsJYp9FYLDQumLzNssLo6UNMNesVwPP1KcgA5atrSqU2w/*`. 

To get the correct answer, you would need 
```[255f0d9b/84'/1'/1/0]tprv8ZgxMBicQKsPerMTN7nhwCpqaAEPkaBCDeE8c9ekAY1xhPmF3HM9r3oz33V8JTwsJYp9FYLDQumLzNssLo6UNMNesVwPP1KcgA5atrSqU2w/84'/1'/1/0/*```

Note the derivation path added in the end. 
See the added test here: https://github.com/sanket1729/rust-miniscript/commit/9c1980247dd1a00aa1ac8a8deb9b89dd14b34c77

**Comment by engenegr** [comment]
@sanket1729 indeed. It works. Thank you for adding new tests. I tried to find some hints from available tests, it was really hard to figure out difference between origin and derivation path.

**Comment by engenegr** [comment]
@sanket1729 could you point may be on examples for using KeyMap for signing PSBTs? Or may be just comment that this structure is not supposed to be used for that purpose.

**Comment by apoelstra** [comment]
@engenegr could you open a fresh issue about this? Right now `KeyMap` does not really provide any facilities for signing, but maybe it should ... I'm not sure. An argument in favor is that this is a "natural" thing to want to do; an argument against is that this library doesn't really know anything about sighashes and tries its damnedest not to do operations on secret keys.

In any case, we certainly should have more documentation and/or examples about this.

**Comment by engenegr** [comment]
@apoelstra sure, no problem. Thanks for reply.
