### ISSUE TITLE
`StrKeyTranslator` excludes `Z`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-miniscript#496]
We have a loop in `test_utils` that reads a little strange
```rust
        for (i, c) in (b'A'..b'Z').enumerate() {
            let key = String::from_utf8(vec![c]).unwrap();
```

Why is Z excluded?

**Comment by apoelstra** [comment]
Lol, I'm sure this was a mistake, though probably not a very important one.
