### ISSUE TITLE
Infinite type-level recursion in `ForEachKey` impl in `Policy`

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-miniscript#541]
In [this code](https://github.com/rust-bitcoin/rust-miniscript/blob/master/src/policy/concrete.rs#L666-L686) we have a method `for_each` which takes a `F: FnMut` and calls itself with an `&mut F`. This causes the compiler to try to instantiate the method with `F`, `&mut F`, `&mut &mut F`, etc., forever. Throughout our codebase, we've avoided this infinite recursion by having an internal `real_for_each` method which directly takes a `&mut F`, so that it can call itself with the same type that it was called with. Then our public-facing `for_each` simply sticks a `&mut` on its argument and calls `real_for_each`.

In the code in question, though, we didn't do this, and for some reason the Rust compiler has accepted it, until tonight. The latest nightly, 2023-04-21, does not compile the code.

Unfortunately this code has been present for a long time (I think since 1.0 of this crate) so to fix it, we will need to backport fixes to ever released version. Fortunately, there are a couple potential fixes, both of which are pretty simple:
* Add a `real_for_each` internal funciton like we do elsewhere
* Change `&mut pred` to `&mut |key| pred(key)` in two places (thanks GPT4 for this one)

See https://github.com/rust-lang/rust/issues/110656

**Comment by sanket1729** [comment]
Interesting. I don't think we should back-port it to every release. How about the releases in the last two years.

**Comment by apoelstra** [comment]
That sounds good to me.

**Comment by sanket1729** [comment]
Actually, @apoelstra the fact the downstream crates did not report any errors means that we should don't need any backports. 

Using this function still results would have still compile error for all versions? I guess that now it results in compile error early on in this library?

**Comment by apoelstra** [comment]
@sanket1729 downstream crates haven't reported any errors because only recent Rust nightlies expose errors. I worry that the next stable version will expose the error and then we'll have trouble.
