### ISSUE TITLE
Bug in `miniscript::interpreter::Interpreter::is_legacy()` for bare script output 

### ISSUE THREAD

**Issue by panicfarm** [rust-bitcoin/rust-miniscript#543]
[Here](https://github.com/rust-bitcoin/rust-miniscript/blob/466dd4904b152f621dc1cce9d403187c62f938bf/src/interpreter/mod.rs#LL359C13-L359C70) this Bare script variant should be `true`, not `false`:
`  inner::Inner::Script(_, inner::ScriptType::Bare) => true,`
We tested it with a P2MS spent output.

**Comment by panicfarm** [comment]
> Agreed. If `Pk` is legacy then `Bare` definitely should be. Good catch!

Can you change it, or we should submit a PR?

**Comment by apoelstra** [comment]
It would be great if you could submit a PR -- I can review and merge it today.

**Comment by panicfarm** [comment]
> It would be great if you could submit a PR -- I can review and merge it today.

Done https://github.com/rust-bitcoin/rust-miniscript/pull/544
