### ISSUE TITLE
Feature request: witness size estimator that understands key availability

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-miniscript#55]
When estimating witness size we should understand which keys (or hash preimages, timelocks, etc) are definitely available, definitely unavailable, or 3rd-party controlled.

**Comment by apoelstra** [comment]
For context - this is something that @sipa, @sanket1729 and I thought we had a simple and efficient algorithm for, but we now believe we were wrong, and don't have a good idea of how to procede. Input from algorithms experts would be appreciated.

**Comment by sanket1729** [comment]
This is being addressed in #481. Really cool that long time issues are being addressed :)

**Comment by apoelstra** [comment]
I think to the extent this issue makes sense, it was addressed by #592 :).
