### ISSUE TITLE
Release v10 with rust-bitcoin v0.30 support

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-miniscript#550]
It's been awhile since rust-bitcoin v0.30 was released, and a new release is in the sight, however, miniscript has not released a crate version supporting bitcoin v0.30 - even though [the PR with the support](https://github.com/rust-bitcoin/rust-miniscript/pull/537) was already merged some time ago.

Can you pls clarify the plans/roadmap for supporting rust-bitcoin v0.30 here?

**Comment by apoelstra** [comment]
Sure, let's use this as a tracking issue.

I think we need to get #493 in first.

@sanket1729 any other blockers?

**Comment by dr-orlovsky** [comment]
With the #551 merged the last thing which is left is the release to crates.io, after which we can close this issue

**Comment by apoelstra** [comment]
Tagged and published.
