### ISSUE TITLE
Wording in the docs, is it an estimation or calculation?

### ISSUE THREAD

**Issue by matthiasdebernardini** [rust-bitcoin/rust-miniscript#555]
[https://docs.rs/miniscript/10.0.0/miniscript/#deriving-an-address-from-a-descriptor](url)

In the docs, `.max_satisfaction_weight()` is described as resulting in an estimation "// Estimate the satisfaction cost."

Why is it an estimation and not a calculation? Is there some ambiguity that is impossible to account for?

**Comment by apoelstra** [comment]
Yes, several:

* With ECDSA signatures, the signatures themselves have variable length, so we just assume that they're always 73 bytes, even though they're most likely to be 71.
* Even with Taproot signatures, they may be 66 bytes (64-byte signature plus sighash flag plus length prefix) but sometimes they'll be 65 (sighash flag is optional)
* If you have an `or` combinator between two policies, they may have different satisfaction costs, and we don't know which one the user is going to/is able to take.
* Same with `thresh`

We are working on a "planning" system #481 which will let you specify which keys are actually available (and not available) which should allow you to get much tighter estimates.

**Comment by matthiasdebernardini** [comment]
Thank you very much!
