### ISSUE TITLE
Why is `Terminal` thus named?

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-miniscript#593]
Why is the `Terminal` name as such when in its a tree node that has children? Why not `Node`?

From the [wiki page on trees](https://en.wikipedia.org/wiki/Tree_(data_structure))

> An internal node (also known as an inner node, inode for short, or branch node) is any node of a tree that has child nodes. Similarly, an external node (also known as an outer node, leaf node, or terminal node) is any node that does not have child nodes.

**Comment by tcharding** [comment]
Excuse my ignorance but I don't understand the `NonTerm` / `Terminal` distinction either?

**Comment by apoelstra** [comment]
This is parsing jargon. Terminals are symbols in the AST. Non-terminals are symbols that only exist during parsing.

The fact that `Terminal` is public and leaks into the type signature of `Miniscript` is an historical accident that we should probably fix, because I agree it's confusing.

**Comment by tcharding** [comment]
Cool, thanks man.
