### ISSUE TITLE
Miniscript website question

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-miniscript#599]
No clue where to ask this question, anyways ...

In @sipa's miniscript site [0] the ripemd160 and hash160 fragments are documented to use OP_SIZE 32 as do the fragments for sha256 and hash256, what does this 32 mean (I'm surprised by it because the outputs are 20 bytes and 32 bytes respectively). What am I missing?

```
len(x) = 32 and SHA256(x) = h | sha256(h) | SIZE <32> EQUALVERIFY SHA256 <h> EQUAL
-- | -- | --
len(x) = 32 and HASH256(x) = h | hash256(h) | SIZE <32> EQUALVERIFY HASH256 <h> EQUAL
len(x) = 32 and RIPEMD160(x) = h | ripemd160(h) | SIZE <32> EQUALVERIFY RIPEMD160 <h> EQUAL
len(x) = 32 and HASH160(x) = h | hash160(h) | SIZE <32> EQUALVERIFY HASH160 <h> EQUAL
```

[0] https://bitcoin.sipa.be/miniscript/

**Comment by tcharding** [comment]
I'm going to close this, its not really the right place to ask.

**Comment by apoelstra** [comment]
For anyone who bumps into this in the future: the 32 is the size of the preimage, and it is there to prevent broken cross-chain swap schemes where an attacker provides a 600-byte preimage (say) which is accepted on the Ethereum chain but not the Bitcoin chain.

**Comment by tcharding** [comment]
Interesting, thanks.
