### ISSUE TITLE
What is the point of all the hash conversion methods in `ToPublicKey`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-miniscript#619]
Currently all implementors of `ToPublicKey` just return the hash argument, what is the point of these trait methods, what am I missing? Is this trait used differently by some other consumer of `rust-miniscript`?

**Comment by apoelstra** [comment]
Yes. The point of these is to convert from an abstract hash value to a concrete one that can be embedded in a script.

Any implementer of `ToPublicKey` that is not working with literal hash values will need to do a nontrivial conversion.

**Comment by apoelstra** [comment]
I'm going to close this. Seems like it's "asked and answered".
