### ISSUE TITLE
`max_satisfaction_weight` is only deprecated for some descriptors

### ISSUE THREAD

**Issue by storopoli** [rust-bitcoin/rust-miniscript#637]
Currently `max_satisfaction_weight` is deprecated only for:

- Generic `Descriptor`
  https://github.com/rust-bitcoin/rust-miniscript/blob/469c113b7258742ba58bf23f9ed3cf8aed514ca8/src/descriptor/mod.rs#L344-L346
- `Bare`
  https://github.com/rust-bitcoin/rust-miniscript/blob/469c113b7258742ba58bf23f9ed3cf8aed514ca8/src/descriptor/bare.rs#L86-L87
- `Sh`
  https://github.com/rust-bitcoin/rust-miniscript/blob/469c113b7258742ba58bf23f9ed3cf8aed514ca8/src/descriptor/sh.rs#L235-L237
- `Wsh`
  https://github.com/rust-bitcoin/rust-miniscript/blob/469c113b7258742ba58bf23f9ed3cf8aed514ca8/src/descriptor/segwitv0.rs#L104-L105
- `tr`
  https://github.com/rust-bitcoin/rust-miniscript/blob/469c113b7258742ba58bf23f9ed3cf8aed514ca8/src/descriptor/tr.rs#L312-L313

but not for:

- `Pkh`:
  https://github.com/rust-bitcoin/rust-miniscript/blob/469c113b7258742ba58bf23f9ed3cf8aed514ca8/src/descriptor/bare.rs#L250-L256
- `Wpkh`:
  https://github.com/rust-bitcoin/rust-miniscript/blob/469c113b7258742ba58bf23f9ed3cf8aed514ca8/src/descriptor/segwitv0.rs#L357-L363

Is this the intended behavior?
If not, I can easily (and gladly) open a PR to add deprecation notices to `Pkh` and `Wpkh`.

Cc @evanlinjin who originally deprecated these.
Related https://github.com/bitcoindevkit/bdk/issues/1036

**Comment by apoelstra** [comment]
I think

* They should be deprecated across the board.
* The deprecation notice should link to discussion in #476 and explain that we redefined what bytes are counted by the method and that the new one will return a different value.
* We should add a `since=10.0.0` field to all the deprecations.

**Comment by storopoli** [comment]
Ok, I'll open a PR later today. Thanks for the clarification :)
