### ISSUE TITLE
Delete `bitcoind_tests`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-miniscript#680]
Should we remove `bitcoind_tests` altogether from `rust-minisicript` and do integration testing in a separate crate, for example in https://github.com/tcharding/bitcoind-tests

The reason for this is that `bitcoincore-rpc` causes problems when trying to release a new version of `rust-bitcoin`.

I believe we need more testing not less but having a dependency on a crate that is not very maintained is a headache for doing releases.

**Comment by apoelstra** [comment]
It is already a different crate :). Do you mean a different repo? I think that would just encourage us to let the tests rot.

Rather than doing this I think we should try to move from bitcoincore-rpc to just directly using rust-jsonrpc.

**Comment by tcharding** [comment]
I have new resolve this morning to solve the `bitcoincore-rpc` problem, and with `electrs` using it this issue is bigger than just `rust-miniscript`.

> It is already a different crate :)

Another dollar :)
