### ISSUE TITLE
`Miniscript.substitute_raw_pkh()` is not recursive

### ISSUE THREAD

**Issue by pythcoiner** [rust-bitcoin/rust-miniscript#728]
I hit a case [here](https://github.com/rust-bitcoin/rust-miniscript/commit/56c05e1795d96fe43330c499571650c8889e0aab) (the last assert fail) where the `RawPkH` seems not substituted.

It looks to me it's due to the fact the method is not recursive and the returned Miniscript is created from the last element of `translated`.

**Comment by apoelstra** [comment]
Fixed by #725
