### ISSUE TITLE
Q: how to understand the htlc examle's relative probability 

### ISSUE THREAD

**Issue by Crayon-Shin-chan-1024** [rust-bitcoin/rust-miniscript#763]
the script:
```
or(10@and(sha256({secret_hash}),pk({redeem_identity})),1@and(older({expiry}),pk({refund_identity})))
```

the miniscript compile output is:
```
<A> OP_CHECKSIG OP_NOTIF
  OP_DUP OP_HASH160 <HASH160(B)> OP_EQUALVERIFY OP_CHECKSIGVERIFY 16
  OP_CHECKSEQUENCEVERIFY
OP_ELSE
  OP_SIZE <20> OP_EQUALVERIFY OP_SHA256 <H> OP_EQUAL
OP_ENDIF
```

if i change the first 10 to some number that smaller than 3,

for exmaple: 
```
or(2@and(sha256({secret_hash}),pk({redeem_identity})),1@and(older({expiry}),pk({refund_identity})))
```

the output is
```
<A> OP_CHECKSIG OP_NOTIF
  <B> OP_CHECKSIGVERIFY 16 OP_CHECKSEQUENCEVERIFY
OP_ELSE
  OP_SIZE <20> OP_EQUALVERIFY OP_SHA256 <H> OP_EQUAL
OP_ENDIF
```
“Why is there such a difference?”

**Comment by apoelstra** [comment]
The probabilites represent the "probability that a given branch will be taken". They are interpreted as a weighting factor for the total spend cost (space in UTXO plus witness space) for the different branches.

In the example you give, by making the first branch much more probable than the second one, the compiler tries to "compress" the second branch by replacing its public key with a public key hash. This reduces the total script size (which must always be paid) *at the expense of increasing the witness size for the second branch* (which is only paid if the second branch is actually taken).

**Comment by Crayon-Shin-chan-1024** [comment]
> The probabilites represent the "probability that a given branch will be taken". They are interpreted as a weighting factor for the total spend cost (space in UTXO plus witness space) for the different branches.
> 
> In the example you give, by making the first branch much more probable than the second one, the compiler tries to "compress" the second branch by replacing its public key with a public key hash. This reduces the total script size (which must always be paid) _at the expense of increasing the witness size for the second branch_ (which is only paid if the second branch is actually taken).

thx for your reply

i have another question, the difference is 
`OP_DUP OP_HASH160 <HASH160(B)> OP_EQUALVERIFY OP_CHECKSIGVERIFY ` and `<B> OP_CHECKSIGVERIFY `

why not just ignore the `OP_DUP OP_HASH160 <HASH160(B)> OP_EQUALVERIFY`

**Comment by apoelstra** [comment]
I'm not sure exactly what you're asking, but `<HASH160(B)>` is 20 bytes long while `<B>` is 32 bytes long. So the one with the hash winds up being several bytes smaller than the one that directly encodes the key.
