### ISSUE TITLE
MSRV [1.63] cleanup: use array::from_fn to avoid mut initialization

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-miniscript#774]
From chatgpt; with MSRV [1.63](https://doc.rust-lang.org/beta/core/array/fn.from_fn.html); you can avoid the mut and creating the actual with all '_' as 
```rust
let mut iter = checksum_str.chars()
let actual: [char; CHECKSUM_LENGTH] = core::array::from_fn(|_| iter.next().expect("Len checked eariler))
```

**Comment by tcharding** [comment]
How did you use chatgpt @sanket1729? Did you just paste a function into it? (I've not managed to find a use for chatgpt with Rust code so far).

**Comment by tcharding** [comment]
Interesting, thanks.
